services:
  backend:
    build:
      context: .  
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"  
    environment:
      DB_HOST: mysql 
      DB_PORT: 3306   
      DB_USER: root   
      DB_PASS: 123   
      DB_NAME: mysql_data  
    depends_on:
      - mysql 
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules 
    networks:
      - mynetwork 

  mysql:
    image: mysql:8.0  
    environment:
      MYSQL_ROOT_PASSWORD: 123  
      MYSQL_DATABASE: mysql_data  
    volumes:
      - mysql_data:/var/lib/mysql  
    networks:
      - mynetwork  

networks:
  mynetwork:
    driver: bridge  

volumes:
  mysql_data:  
